version: "3.9"

volumes:
  data:

services:
  formatter:
    build:
      context: .
      dockerfile: Dockerfile.1
    command: black .
  linter:
    build:
      context: .
      dockerfile: Dockerfile.1
    depends_on:
      formatter:
        condition: service_completed_successfully
    command: flake8 .
  static-type-checker:
    build:
      context: .
      dockerfile: Dockerfile.1
    depends_on:
      formatter:
        condition: service_completed_successfully
    command: mypy
  tests:
    build:
      context: .
      dockerfile: Dockerfile.1
    depends_on:
      linter:
        condition: service_completed_successfully
      static-type-checker:
        condition: service_completed_successfully
    command: pytest